name: ostad_flutter_batch_two
description: Flutter project for ostad batch two live class


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  path_provider: ^2.0.14
  shared_preferences: ^2.0.18
  image_picker: ^0.8.6+4
  firebase_messaging: ^14.4.0
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
