name: ostad_flutter_batch_two
description: Flutter project for ostad batch two live class


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  http: ^0.13.5
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
